#!/usr/bin/env bash



export OTEL_SERVICE_NAME="openhands-cli"

export OTEL_TRACES_EXPORTER="otlp"
export OTEL_LOGS_EXPORTER="otlp"
export OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf"
export OTEL_EXPORTER_OTLP_ENDPOINT="http://host.docker.internal:4318" # local collector
export OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true

export OTEL_DEBUG=true
export OTEL_LOG_LEVEL=info

## Log levels (not case-sensitive) for --log-level
# _nameToLevel = {
#     'CRITICAL': CRITICAL,
#     'FATAL': FATAL,
#     'ERROR': ERROR,
#     'WARN': WARNING,
#     'WARNING': WARNING,
#     'INFO': INFO,
#     'DEBUG': DEBUG,
#     'NOTSET': NOTSET,
# }
# CRITICAL = 50
# FATAL = CRITICAL
# ERROR = 40
# WARNING = 30
# WARN = WARNING
# INFO = 20
# DEBUG = 10
# NOTSET = 0

project_name=${1:-"simple-web-page"}
echo "Project name: $project_name"

# export SANDBOX_VOLUMES="/workspaces/mtg-deck-shuffler:/workspace:rw"
# export TEAM=gamenite
if [ "$project_name" = "mtg-deck-shuffler" ]; then
  export SANDBOX_VOLUMES="/workspaces/mtg-deck-shuffler:/workspace:rw"
  export TEAM=gamenite
elsif [ "$project_name" = "simple-web-page" ]; then
  export SANDBOX_VOLUMES="/workspaces/simple-web-page:/workspace:rw"
  export TEAM=web
elsif [ "$project_name" = "openhands" ]; then
  export SANDBOX_VOLUMES="/workspaces/openhands:/workspace:rw"
  export TEAM=platform
else
  if [ ! -d "/workspaces/$project_name" ]; then
    echo "Project $project_name does not exist"
    exit 1
  fi
  export SANDBOX_VOLUMES="/workspaces/$project_name:/workspace:rw"
  export TEAM=$project_name
fi

# If you haven't yet:
# poetry install

poetry run opentelemetry-instrument --logs_exporter otlp --metrics_exporter none python -m openhands.cli.main  # --log-level info
