#!/usr/bin/env bash



export OTEL_SERVICE_NAME="openhands-cli"

export OTEL_TRACES_EXPORTER="otlp"
export OTEL_LOGS_EXPORTER="otlp"
export OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf"
export OTEL_EXPORTER_OTLP_ENDPOINT="http://host.docker.internal:4318" # local collector
export OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true

export OTEL_DEBUG=true
export OTEL_LOG_LEVEL=info

## Log levels (not case-sensitive) for --log-level
# _nameToLevel = {
#     'CRITICAL': CRITICAL,
#     'FATAL': FATAL,
#     'ERROR': ERROR,
#     'WARN': WARNING,
#     'WARNING': WARNING,
#     'INFO': INFO,
#     'DEBUG': DEBUG,
#     'NOTSET': NOTSET,
# }
# CRITICAL = 50
# FATAL = CRITICAL
# ERROR = 40
# WARNING = 30
# WARN = WARNING
# INFO = 20
# DEBUG = 10
# NOTSET = 0

export SANDBOX_VOLUMES="/workspaces/simple-web-page:/workspace:rw"

# If you haven't yet:
# poetry install

poetry run opentelemetry-instrument --logs_exporter otlp --metrics_exporter none python -m openhands.cli.main  # --log-level info
